{{- if .Values.webhook.enabled }}
{{- if .Values.webhook.service.create }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "dns-operator.webhookServiceName" . }}
  namespace: {{ include "dns-operator.namespace" . }}
  labels:
    {{- include "dns-operator.labels" . | nindent 4 }}
spec:
  ports:
    - port: {{ .Values.webhook.service.port }}
      protocol: TCP
      targetPort: {{ .Values.webhook.service.targetPort }}
  selector:
    {{- include "dns-operator.selectorLabels" . | nindent 4 }}
{{- end }}
{{- end }}
